import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "./../apollo-client";

export default function Home() {
  const [countries, setcountries] = React.useState([]);
  const [loading, setloading] = React.useState(false);
  React.useEffect(async() => {
  //  handleCountry()
  }, []);
  const handleCountry = async() =>{
    const { data,loading,error } = await client.query({
      query: gql`
        query Countries {
          countries {
            code
            name
            emoji
          }
        }
      `,
    });
    if(error) console.log(error)
    if(loading) setloading(true)
    if(data)setcountries(data.countries);setloading(false)
  }
  const handleState = async(countryCode) =>{
    const { data,loading,error } = await client.query({
      query: gql`
        query Countries ($code: ID!){
          country(code: $code) {
            states {
              code
              name
              country {
                name
              }
            }
          }
        }
      `,
      variables: {
        "code": countryCode
      }
    });
    if(error) console.log(error)
    if(loading) setloading(true)
    if(data)setcountries(data.country.states);setloading(false)
  }
  if(loading) return <div>Loading</div>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {countries.length>0 && countries.map((ele,index)=>{
            return <a onClick={()=>ele.country?handleCountry():handleState(ele.code)} key={index} className={styles.card}>
            <h2>{ele.name} &rarr;</h2>
            <p>{`${ele.code}`}</p>
          </a>
          })}
          {countries.length===0 && <><a onClick={()=>handleCountry()} className={styles.card}>
            <h2>No State Here &rarr;</h2>
          </a></>}
          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
